#!/bin/sh

mkdir $HOME/bin
cp bin/* $HOME/bin

mkdir -p $HOME/.config/systemd/user
cp systemd.d/* $HOME/.config/systemd/user

systemctl --user daemon-reload

echo -n 'Checking for sudo...'

if ! lvu installed sudo >/dev/null
then
    echo 'ok'
else
    echo 'sudo not installed'
    echo -n "Enter root's "
    su -c 'lin sudo'
    echo -n "Enter root's "
    su -c 'echo "'$(whoami)' ALL=(ALL) NOPASSWD: ALL >> /etc/sudoers'
fi

echo -n 'Checking for git...'

if lvu installed git > /dev/null
then
    echo 'ok'
else
    echo 'git not installed'
    sudo lin git
fi
