#!/bin/sh

mkdir -p $HOME/bin
cp bin/* $HOME/bin

mkdir -p $HOME/.config/systemd/user
cp systemd.d/* $HOME/.config/systemd/user

systemctl --user daemon-reload

echo -n 'Checking for sudo...'

if lvu installed sudo >/dev/null
then
    echo 'ok'
else
    echo 'sudo not installed'
    echo -n "Enter root's "
    su -c 'lin sudo'
    echo -n "Enter root's "
    su -c 'echo "'$(whoami)' ALL=(ALL) NOPASSWD: ALL" >> /etc/sudoers'
fi


for module in lz4 libisoburn syslinux efitools squashfs git;do
    echo -n "Checking for ${module}..."
    if lvu installed $module > /dev/null
    then
        echo 'ok'
    else
        echo $module 'not installed'
        sudo lin $module
    fi
done
